FROM tensorflow/tensorflow:2.3.0-gpu
COPY DockQ/ /home/
RUN  apt update -y
RUN  apt-get install apt-utils -y
RUN  apt-get install dssp -y
RUN  DEBIAN_FRONTEND=noninteractive apt-get install python3-tk -y
RUN  python -m pip install keras
RUN  python -m pip install matplotlib
RUN  python -m pip install biopython
RUN  python -m pip install seaborn
RUN  python -m pip install sklearn
RUN  python -m pip install jupyter
RUN  python -m pip install pandas
RUN  cd /home/DockQ/
RUN  make
